[package]
name = "floor-tile-cost-calculator"
version = "0.1.0"
authors = ["Daniel Meskin <github@dmeskin.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
