[package]
name = "credit-card-validator-cheating"
version = "0.1.0"
authors = ["Daniel Meskin <github@dmeskin.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
card-validate = "2.2.2"